name: Publicacion Automatica

on:
  push:
    tags:
      - 'v*' # Se activa cuando creas una versi√≥n como v1.0

jobs:
  build:
    name: Compilando para Android y Windows
    runs-on: windows-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Compilar para Android
        run: flutter build apk --release

      - name: Compilar para Windows
        run: |
          flutter config --enable-windows-desktop
          flutter build windows --release
          
      - name: Crear Release y Subir Archivos
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            build/windows/runner/Release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
